---
- block:

  - name: Install docksal
    include: "{{ role_path }}/tasks/install_docksal.yml"
    tags: ['install']

  - name: Uninstall docksal
    include: "{{ role_path }}/tasks/uninstall_docksal.yml"
    tags: ['uninstall']
