---
- block:
  - name: Remove andock-ci user
    user:
      name: andock-ci
      remove: yes
      force: yes
    become: true

  - name: fin uninstall
    file:
      state: absent
      path: "/usr/local/bin/fin"
    become: true